docker run -it -d \
  --label traefik.http.routers.kyccmicrofinance.rule=Host\(\`kyccmicrofinance.online\`\) \
  --label traefik.http.routers.kyccmicrofinance.tls.certresolver=lets-encrypt \
  --label traefik.http.routers.kyccmicrofinance.tls=true \
  --label traefik.http.routers.kyccmicrofinance.service=kyccmicrofinance-credit-http \
  --label traefik.http.services.kyccmicrofinance-credit-http.loadbalancer.server.port=80 \
  --name kyccmicrofinance \
  --network web \
  --restart always \
  --expose 80 \
mikoposoft/nackcredit:latest 













