docker run -it -d \
  --label traefik.http.routers.wjkmicrofinance.rule=Host\(\`wjkmicrofinance.online\`\) \
  --label traefik.http.routers.wjkmicrofinance.tls.certresolver=lets-encrypt \
  --label traefik.http.routers.wjkmicrofinance.tls=true \
  --label traefik.http.routers.wjkmicrofinance.service=wjkmicrofinance-credit-http \
  --label traefik.http.services.wjkmicrofinance-credit-http.loadbalancer.server.port=80 \
  --name wjkmicrofinance \
  --network web \
  --restart always \
  --expose 80 \
mikoposoft/nackcredit:12dec2025













