<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title><?php echo htmlspecialchars($compdata->comp_name, ENT_QUOTES, 'UTF-8'); ?> | FLOAT TRANSFER REPORT</title>
</head>
<body>
<div id="container">
  <style>
    body { font-family: arial, sans-serif; font-size: 12px; margin: 0; padding: 0; }
    .c { text-transform: uppercase; }
    table { border-collapse: collapse; width: 100%; }
    th { background-color: #00bcd4; color: #ffffff; font-size: 11px; padding: 6px 8px; text-align: left; border: 1px solid #ccc; }
    td { font-size: 11px; padding: 5px 8px; border: 1px solid #e0e0e0; }
    tr:nth-child(even) td { background-color: #f2f2f2; }
    .total-row td { background-color: #ddd; font-weight: bold; }
    .text-right { text-align: right; }
    .header-table td { border: none; }
    .divider { border: 0; border-top: 2px solid #00bcd4; margin: 8px 0 10px; }
  </style>

  <!-- Company Header -->
  <table class="header-table" style="width: 100%; margin-bottom: 4px;">
    <tr>
      <td style="width: 100px; vertical-align: middle;">
        <?php
          $logo_path = FCPATH . 'assets/img/' . ($compdata->comp_logo ?? '');
          if (!empty($compdata->comp_logo) && is_file($logo_path)):
        ?>
          <img src="<?php echo $logo_path; ?>" style="width: 80px; height: 65px; object-fit: contain;">
        <?php endif; ?>
      </td>
      <td style="text-align: center; vertical-align: middle;">
        <p style="font-size:15px; margin: 0;" class="c">
          <b><?php echo htmlspecialchars($compdata->comp_name, ENT_QUOTES, 'UTF-8'); ?></b>
        </p>
        <p style="font-size:11px; margin: 2px 0;">
          <?php echo htmlspecialchars($compdata->adress ?? '', ENT_QUOTES, 'UTF-8'); ?>
        </p>
        <p style="font-size:13px; margin: 4px 0;" class="c"><b>FLOAT TRANSFER REPORT</b></p>
        <?php if (!empty($from) || !empty($to)): ?>
          <p style="font-size:10px; margin: 2px 0;">
            From: <?php echo !empty($from) ? htmlspecialchars($from, ENT_QUOTES, 'UTF-8') : '-'; ?>
            &nbsp;&nbsp;|&nbsp;&nbsp;
            To: <?php echo !empty($to) ? htmlspecialchars($to, ENT_QUOTES, 'UTF-8') : '-'; ?>
          </p>
        <?php endif; ?>
        <p style="font-size:10px; margin: 2px 0; color: #555;">
          Printed: <?php echo date('d M Y, H:i'); ?>
        </p>
      </td>
    </tr>
  </table>

  <hr class="divider">

  <!-- Data Table -->
  <table>
    <thead>
      <tr>
        <th style="width: 35px;">No.</th>
        <th>From Account</th>
        <th style="text-align:right;">Amount</th>
        <th>To Branch</th>
        <th>To Branch Account</th>
        <th style="text-align:right;">Withdrawal Charges</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
      <?php if (!empty($float)):
        $no = 1;
        foreach ($float as $row): ?>
        <tr>
          <td><?php echo $no++; ?></td>
          <td class="c"><?php echo htmlspecialchars($row->from_account ?? '-', ENT_QUOTES, 'UTF-8'); ?></td>
          <td class="text-right"><?php echo number_format((float)($row->blanch_amount ?? 0)); ?></td>
          <td class="c"><?php echo htmlspecialchars($row->blanch_name ?? '-', ENT_QUOTES, 'UTF-8'); ?></td>
          <td class="c"><?php echo htmlspecialchars($row->to_account ?? '-', ENT_QUOTES, 'UTF-8'); ?></td>
          <td class="text-right"><?php echo number_format((float)($row->charger ?? 0)); ?></td>
          <td><?php echo htmlspecialchars(date('d M Y', strtotime($row->trans_day)), ENT_QUOTES, 'UTF-8'); ?></td>
        </tr>
      <?php endforeach;
      else: ?>
        <tr>
          <td colspan="7" style="text-align: center; color: #888;">No records found.</td>
        </tr>
      <?php endif; ?>
    </tbody>
    <tfoot>
      <tr class="total-row">
        <td colspan="2"><b>TOTAL</b></td>
        <td class="text-right"><b><?php echo number_format((float)($total_amount ?? 0)); ?></b></td>
        <td colspan="2"></td>
        <td class="text-right"><b><?php echo number_format((float)($total_chargers ?? 0)); ?></b></td>
        <td></td>
      </tr>
    </tfoot>
  </table>

  <p style="font-size: 9px; color: #888; text-align: center; margin-top: 16px;">
    Generated by Brainsoft Technology &mdash; <?php echo date('d M Y H:i:s'); ?>
  </p>
</div>
</body>
</html>
